image: node:20.17

pipelines:
  default:
    - step:
        name: Build and Deploy
        caches:
          - node
        script:
          - npm install
          - npm run build
          - npm install -g vercel
          - vercel --prod --token $VERCEL_TOKEN
