name: Deploy to Vercel

on:
  push:
    branches:
      - main # Dispara o deploy em cada push na branch main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Faz o checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # Instala Node.js na versão especificada
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Defina a versão do Node.js que seu projeto usa

      # Instala dependências
      - name: Install dependencies
        run: npm install

      # Executa o build da aplicação
      - name: Build the project
        run: npm run build

      # Faz o deploy no Vercel
      - name: Deploy to Vercel
        run: npx vercel --prod --yes --token ${{ secrets.VERCEL_TOKEN }}
